### ISSUE TITLE
PyInquirer error when starting gonha

### ISSUE THREAD

**Issue by ragouel** [fredcox/gonha#1]
Arch Linux 5.4.50-1-lts
Python version: 3.8.3

<pre><code>Traceback (most recent call last):
  File "/usr/bin/gonha", line 2, in <module>
    import gonha
  File "/usr/lib/python3.8/site-packages/gonha/__init__.py", line 12, in <module>
    from PyInquirer import prompt, print_json
  File "/usr/lib/python3.8/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/usr/lib/python3.8/site-packages/prompt_toolkit/token.py)</code></pre>

**Comment by fredcox** [comment]
Hi, Ragouel, 

Can you put the file $HOME/.config/gonha/config.json here? Thank you.

**Comment by fredcox** [comment]
What´s the output from following command in your terminal?
`$ pip3 install PyInquirer`

Copy and paste here

**Comment by ragouel** [comment]
`cat ~/.config/gonha/config.ini`

<pre><code>[DEFAULT]
position = topRight
iface = </code></pre>

I'm not using `pip` to install PyInquirer, I'm using Pacman to resolve dependencies.
[python-pyinquirer](https://aur.archlinux.org/packages/python-pyinquirer/)

`$ pip3 install PyInquirer`
<pre><code>Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyInquirer in /usr/lib/python3.8/site-packages (1.0.2)
Collecting prompt_toolkit==1.0.14
  Downloading prompt_toolkit-1.0.14-py3-none-any.whl (248 kB)
     |████████████████████████████████| 248 kB 655 kB/s 
Requirement already satisfied: Pygments>=2.2.0 in /usr/lib/python3.8/site-packages (from PyInquirer) (2.6.1)
Requirement already satisfied: regex>=2016.11.21 in /usr/lib/python3.8/site-packages (from PyInquirer) (2020.6.8)
Requirement already satisfied: wcwidth in /usr/lib/python3.8/site-packages (from prompt_toolkit==1.0.14->PyInquirer) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3.8/site-packages (from prompt_toolkit==1.0.14->PyInquirer) (1.15.0)
Installing collected packages: prompt-toolkit
Successfully installed prompt-toolkit-1.0.14</code></pre>

**Comment by fredcox** [comment]
> `cat ~/.config/gonha/config.ini`
> 
> ```
> [DEFAULT]
> position = topRight
> iface = 
> ```
> 
> I'm not using `pip` to install PyInquirer, I'm using Pacman to resolve dependencies.
> [python-pyinquirer](https://aur.archlinux.org/packages/python-pyinquirer/)
> 
> `$ pip3 install PyInquirer`
> 
> ```
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: PyInquirer in /usr/lib/python3.8/site-packages (1.0.2)
> Collecting prompt_toolkit==1.0.14
>   Downloading prompt_toolkit-1.0.14-py3-none-any.whl (248 kB)
>      |████████████████████████████████| 248 kB 655 kB/s 
> Requirement already satisfied: Pygments>=2.2.0 in /usr/lib/python3.8/site-packages (from PyInquirer) (2.6.1)
> Requirement already satisfied: regex>=2016.11.21 in /usr/lib/python3.8/site-packages (from PyInquirer) (2020.6.8)
> Requirement already satisfied: wcwidth in /usr/lib/python3.8/site-packages (from prompt_toolkit==1.0.14->PyInquirer) (0.2.5)
> Requirement already satisfied: six>=1.9.0 in /usr/lib/python3.8/site-packages (from prompt_toolkit==1.0.14->PyInquirer) (1.15.0)
> Installing collected packages: prompt-toolkit
> Successfully installed prompt-toolkit-1.0.14
> ```

You need now upgrade to latest version 0.1.34, running the following command:
`$ pip3 install gonha --upgrade`

run the command above until the pip3 found the latest version. 

After this i think will be right. 

best regards

**Comment by fredcox** [comment]
By the wall, the package [python-pyinquirer](https://aur.archlinux.org/packages/python-pyinquirer/) you installed is broken and with bugs. 

The only command and no problem.
`$ pip3 install gonha --upgrade`

**Comment by ragouel** [comment]
Yep, issue is resolved.

**Comment by yochananmarqos** [comment]
@ragouel How? There's no difference with `gonha` or `gonha-git`.

**Comment by ragouel** [comment]
@yochananmarqos clean up AUR cache and try again. Issue is resolved on my end.

**Comment by yochananmarqos** [comment]
@ragouel I did a clean build of both packages with no difference.

**Comment by ragouel** [comment]
Did you `rm -rf ~/.config/gonha` too ?

**Comment by yochananmarqos** [comment]
@ragouel It hasn't successfully run yet, so it's never created one.

**Comment by ragouel** [comment]
Post an strace log

**Comment by yochananmarqos** [comment]
That doesn't seem very helpful.
```
$ strace gonha
execve("/usr/sbin/gonha", ["gonha"], 0x7ffcff07f9e0 /* 68 vars */) = -1 ENOENT (No such file or directory)
strace: exec: No such file or directory
+++ exited with 1 +++
```

It's still doing the same thing I posted on the `gonha-git` AUR page:
```
gonha
Traceback (most recent call last):
  File "/usr/sbin/gonha", line 2, in <module>
    import gonha
  File "/usr/lib/python3.8/site-packages/gonha/__init__.py", line 12, in <module>
    from PyInquirer import prompt, print_json
  File "/usr/lib/python3.8/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/usr/lib/python3.8/site-packages/prompt_toolkit/token.py)
```

**Comment by ragouel** [comment]
Why is `gonha` located in `/usr/sbin` ? I never place binaries there.

**Comment by yochananmarqos** [comment]
`/usr/sbin/` is a symlink to `/usr/bin/` and is not related to the issue.

**Comment by ragouel** [comment]
This makes no sense. I'm assuming your system is updated, right ?

**Comment by yochananmarqos** [comment]
Yes, of course. 

It looks like you installed the dependencies with `pip`, that could be why it's working for you.

**Comment by ragouel** [comment]
I didn't,I used Pacman. I just noticed the Manjaro logo on your avatar. Are you using Manjaro, and if so, did you check to see if the Manjaro deps are synced with Arch ?

**Comment by fredcox** [comment]
> Yes, of course.
> 
> It looks like you installed the dependencies with `pip`, that could be why it's working for you.

Hi, please install with
`$ pip3 install gonna `

You not will be problem. It's ok

**Comment by ragouel** [comment]
Nah Fred, we need to get to the bottom of this. The fate of the universe is at stake here.

**Comment by ragouel** [comment]
@yochananmarqos So, I investigated a bit more and turns out you were right. There was a version of prompt_toolkit 1.0.14 in my HOME folder I didn't uninstall through `pip` (God, I hate that name!). So, I uploaded a [PKGBUILD](https://aur.archlinux.org/packages/python-prompt_toolkit1014/)  of that version and it now runs.
