### ISSUE TITLE
STDOUT spams locale in terminal

### ISSUE THREAD

**Issue by yochananmarqos** [fredcox/gonha#11]
With the latest commit, running from the terminal posts the locale over and over while it's running. 

```
❯ gonha
2020-08-07 08:26:25 inspirognome __main__[251446] INFO :: Gonha - 1.6.42 ::
2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Starting...
en_US
2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Screen: eDP
2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Screen Resolution: 1920 x 1080
2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Available space for gonha: 1862 x 1022
en_US
en_US
en_US
en_US
en_US
en_US
en_US
```

**Comment by fredcox** [comment]
> t commit, running from the terminal posts the locale over and over while it's running.

Please , run the latest version is 1.7.2

**Comment by fredcox** [comment]
> With the latest commit, running from the terminal posts the locale over and over while it's running.
> 
> ```
> ❯ gonha
> 2020-08-07 08:26:25 inspirognome __main__[251446] INFO :: Gonha - 1.6.42 ::
> 2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Starting...
> en_US
> 2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Screen: eDP
> 2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Screen Resolution: 1920 x 1080
> 2020-08-07 08:26:25 inspirognome gonha.mainwindow[251446] INFO Available space for gonha: 1862 x 1022
> en_US
> en_US
> en_US
> en_US
> en_US
> en_US
> en_US
> ```

Release 1.7.4 out now and fully ok.

**Comment by yochananmarqos** [comment]
I installed `i18n` which should only require `babel` and `py`, right?

```
Traceback (most recent call last):
  File "/usr/sbin/gonha", line 3, in <module>
    from gonha.mainwindow import MainWindow
  File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 4, in <module>
    from gonha.threads import *
  File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 2, in <module>
    from gonha.util import Config
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 181, in <module>
    class Config:
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 191, in Config
    lang = Language()
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 36, in __init__
    i18n.set('filename_format', '{locale}.{format}')
AttributeError: module 'i18n' has no attribute 'set'
```

**Comment by fredcox** [comment]
> equire `babel` and `py`, right?

you must install python-i18n and Babel not i18n only.

**Comment by fredcox** [comment]
> I installed `i18n` which should only require `babel` and `py`, right?
> 
> ```
> Traceback (most recent call last):
>   File "/usr/sbin/gonha", line 3, in <module>
>     from gonha.mainwindow import MainWindow
>   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 4, in <module>
>     from gonha.threads import *
>   File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 2, in <module>
>     from gonha.util import Config
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 181, in <module>
>     class Config:
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 191, in Config
>     lang = Language()
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 36, in __init__
>     i18n.set('filename_format', '{locale}.{format}')
> AttributeError: module 'i18n' has no attribute 'set'
> ```
> 
> `i18n` hasn't been updated for 8 years, are you sure you want to use it?

i am using python-i18n pypi package.

**Comment by yochananmarqos** [comment]
> you must install python-i18n and Babel not i18n only.

Yes, I know. I was talking about `i18n`'s dependencies. If you're going to keep it around, I'll need to add it to the AUR.

**Comment by yochananmarqos** [comment]
> i am using python-i18n pypi package.

Oops. I installed `i18n`, not `python-i18n`. I'll try that.

**Comment by yochananmarqos** [comment]
It's working now with the proper dependencies.
