### ISSUE TITLE
[Feature Request] AMDGPU support

### ISSUE THREAD

**Issue by yochananmarqos** [fredcox/gonha#6]
I see you added NVIDIA support, what about AMD?

**Comment by fredcox** [comment]
> I see you added NVIDIA support, what about AMD?

Hi, yes i add nvidia gpu support. And we will add support for amd gpus, but we need wait for @fagianijunior . @fagianijunior is developer this project too and will developer the amd gpu support. 

regards

**Comment by fredcox** [comment]
> > I see you added NVIDIA support, what about AMD?
> 
> Hi, yes i add nvidia gpu support. And we will add support for amd gpus, but we need wait for @fagianijunior . @fagianijunior is developer this project too and will developer the amd gpu support.
> 
> regards

Hi, friend. The amd gpu support is out now in release 1.6.38. 

best regards

**Comment by yochananmarqos** [comment]
The VRAM and temperature is reported, but it does not display the model. That may be because I have an APU, not a dedicated GPU.

```
CPU:       Topology: Quad Core model: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx bits: 64 type: MT MCP L2 cache: 2048 KiB 
           Speed: 2018 MHz min/max: 1600/2000 MHz Core speeds (MHz): 1: 2791 2: 2792 3: 1503 4: 1434 5: 1534 6: 1546 7: 2783 
           8: 2077 
Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] driver: amdgpu v: kernel 
           Device-2: Realtek Integrated Webcam type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu unloaded: modesetting resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.38.0 5.8.0-1-MANJARO LLVM 10.0.1) v: 4.6 Mesa 20.1.4 
```

**Comment by fredcox** [comment]
> The VRAM and temperature is reported, but it does not display the model. That may be because I have an APU, not a dedicated GPU.
> 
> ```
> CPU:       Topology: Quad Core model: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx bits: 64 type: MT MCP L2 cache: 2048 KiB 
>            Speed: 2018 MHz min/max: 1600/2000 MHz Core speeds (MHz): 1: 2791 2: 2792 3: 1503 4: 1434 5: 1534 6: 1546 7: 2783 
>            8: 2077 
> Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] driver: amdgpu v: kernel 
>            Device-2: Realtek Integrated Webcam type: USB driver: uvcvideo 
>            Display: x11 server: X.Org 1.20.8 driver: amdgpu unloaded: modesetting resolution: 1920x1080~60Hz 
>            OpenGL: renderer: AMD RAVEN (DRM 3.38.0 5.8.0-1-MANJARO LLVM 10.0.1) v: 4.6 Mesa 20.1.4 
> ```

Yes, the amd gpu feature is only to amd Radeon gpus.you have one Radeon Vega serie APU

**Comment by fagianijunior** [comment]
I does not has a APU to try this, but, it is crashing for you? or only does not show the model name?

**Comment by yochananmarqos** [comment]
> only does not show the model name

Indeed.
