### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yochananmarqos** [fredcox/gonha#7]
Just had this error pulling from the latest commit with newly regenerated config file:

```
::  Gonha 1.5.3  ::
Starting...

Traceback (most recent call last):
  File "/usr/sbin/gonha", line 13, in <module>
    window = MainWindow()
  File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 143, in __init__
    for w in self.wins:
  File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 142, in <lambda>
    self.wins = filter(lambda wHandle: wHandle.get_wm_class()[1] == 'gonha', self.all_wins)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by fredcox** [comment]
> Just had this error pulling from the latest commit with newly regenerated config file:
> 
> ```
> ::  Gonha 1.5.3  ::
> Starting...
> 
> Traceback (most recent call last):
>   File "/usr/sbin/gonha", line 13, in <module>
>     window = MainWindow()
>   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 143, in __init__
>     for w in self.wins:
>   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 142, in <lambda>
>     self.wins = filter(lambda wHandle: wHandle.get_wm_class()[1] == 'gonha', self.all_wins)
> TypeError: 'NoneType' object is not subscriptable
> ```

Hi, 

Please delete the file ~/home/.config/config.json and run pip3 install gonna --upgrade

**Comment by fredcox** [comment]
> > Just had this error pulling from the latest commit with newly regenerated config file:
> > ```
> > ::  Gonha 1.5.3  ::
> > Starting...
> > 
> > Traceback (most recent call last):
> >   File "/usr/sbin/gonha", line 13, in <module>
> >     window = MainWindow()
> >   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 143, in __init__
> >     for w in self.wins:
> >   File "/usr/lib/python3.8/site-packages/gonha/mainwindow.py", line 142, in <lambda>
> >     self.wins = filter(lambda wHandle: wHandle.get_wm_class()[1] == 'gonha', self.all_wins)
> > TypeError: 'NoneType' object is not subscriptable
> > ```
> 
> Hi,
> 
> Please delete the file /home/yourusername/.config/gonha/config.json and run pip3 install gonna --upgrade

And no install pip3 package as superuser. It is not necessary. You need uninstall gonha global install and reinstall for your user with command pip3 install gonha --upgrade without sudo

**Comment by yochananmarqos** [comment]
I deleted the config file, pulled the latest commit, replaced `colr` with `coloredlogs` and now get this:

```
2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO :: Gonha - 1.5.5 ::
2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Starting...
2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO 
2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Screen: eDP
2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Screen Resolution: 1920 x 1080
2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Available space for gonha: 1862 x 1022
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 208, in run
    devices = self.smart.getDevicesHealth()
  File "/usr/lib/python3.8/site-packages/gonha/util.py", line 60, in getDevicesHealth
    temp = int(temp)
ValueError: invalid literal for int() with base 10: ''
zsh: abort (core dumped)  gonha
```

By the way, I'm the Co-Maintainer of the [`gonha`](https://aur.archlinux.org/packages/gonha) and [`gonha-git`](https://aur.archlinux.org/packages/gonha-git) AUR packages. I'm not using Pip.

**Comment by fredcox** [comment]
> I deleted the config file, pulled the latest commit, replaced `colr` with `coloredlogs` and now get this:
> 
> ```
> 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO :: Gonha - 1.5.5 ::
> 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Starting...
> 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO 
> 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Screen: eDP
> 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Screen Resolution: 1920 x 1080
> 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Available space for gonha: 1862 x 1022
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 208, in run
>     devices = self.smart.getDevicesHealth()
>   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 60, in getDevicesHealth
>     temp = int(temp)
> ValueError: invalid literal for int() with base 10: ''
> zsh: abort (core dumped)  gonha
> ```
> 
> By the way, I'm the Co-Maintainer of the [`gonha`](https://aur.archlinux.org/packages/gonha) and [`gonha-git`](https://aur.archlinux.org/packages/gonha-git) AUR packages. I'm not using Pip.

OK. Do you enable smartctl and nvme-cli without password for your user ?

**Comment by fredcox** [comment]
> > I deleted the config file, pulled the latest commit, replaced `colr` with `coloredlogs` and now get this:
> > ```
> > 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO :: Gonha - 1.5.5 ::
> > 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Starting...
> > 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO 
> > 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Screen: eDP
> > 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Screen Resolution: 1920 x 1080
> > 2020-07-31 15:20:28 inspirognome gonha.mainwindow[1051232] INFO Available space for gonha: 1862 x 1022
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/site-packages/gonha/threads.py", line 208, in run
> >     devices = self.smart.getDevicesHealth()
> >   File "/usr/lib/python3.8/site-packages/gonha/util.py", line 60, in getDevicesHealth
> >     temp = int(temp)
> > ValueError: invalid literal for int() with base 10: ''
> > zsh: abort (core dumped)  gonha
> > ```
> > 
> > 
> > By the way, I'm the Co-Maintainer of the [`gonha`](https://aur.archlinux.org/packages/gonha) and [`gonha-git`](https://aur.archlinux.org/packages/gonha-git) AUR packages. I'm not using Pip.
> 
> OK. Do you enable smartctl and nvme-cli without password for your user ?

I will check about sudo commands without passwords in gonha core on execution. If check fail, the gonha will refused with error dialog. 

I will implement this now

**Comment by yochananmarqos** [comment]
> Do you enable smartctl and nvme-cli without password for your user ?

After starting `smartd.service`, it prompted for my sudo password and runs fine.

`nvme-cli` should not be needed (I do have it installed, but nothing running) since NVME monitoring is supported in kernel >=5.5 via HWMON.

**Comment by fredcox** [comment]
> ddt

Ah, ok. hddtemp is a very old and the not updated for years later. The developer not updated hddtemp, so the program become obsolete and not support nvme´s.  I choose smartmontools because suport two technologies (sata and nvme), and smartmontools work in switch with nvme-cli.

**Comment by fredcox** [comment]
> > Do you enable smartctl and nvme-cli without password for your user ?
> 
> After starting `smartd.service`, it prompted for my sudo password and runs fine.
> 
> `nvme-cli` should not be needed (I do have it installed, but nothing running) since NVME monitoring is supported in kernel >=5.5 via HWMON.
> 
> EDIT: Why use `smartmontools` when you can use `hddtemp`? It doesn't require sudo if running as a daemon. Then only `hddtemp` would be required instead of both `smartmontools` and `nvme-cli`.

You are reason, nvme-cli is necessary only if the user have one nvme in system. So, i switch to another form of gatering information about this, and i will change de wizard with what type kind SSD or nvme technology the user want to monitoring.

**Comment by yochananmarqos** [comment]
It doesn't matter if `hddtemp` supports NVME monitoring or not because the kernel supports it via HWMON like I said.

**Comment by fredcox** [comment]
> It doesn't matter if `hddtemp` supports NVME monitoring or not because the kernel supports it via HWMON like I said.

Ok,
